"""move project data into per-project db

Revision ID: 37048de48438
Revises: a7068caf07cf
Create Date: 2026-08-30 11:06:37.172475

项目从此可以放在磁盘任意位置，运行数据跟着目录走：素材、任务、会话、记忆、草稿
这些表整体迁到 `{项目目录}/.atelier/project.db`（建表见 alembic/project 那套迁移），全局
库只留机器级数据，另外多一张 `project_registry` 记住本机打开过哪些项目、在哪。

旧库里这些表本期还没接上业务代码，内容也能从项目目录重建，所以直接 drop，不做
数据搬运；downgrade 只还原表结构，不还原数据。
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import sqlite

revision: str = '37048de48438'
down_revision: str | None = 'a7068caf07cf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_registry',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('dir_path', sa.String(length=1024), nullable=False),
    sa.Column('managed', sa.Boolean(), nullable=False),
    sa.Column('missing', sa.Boolean(), nullable=False),
    sa.Column('last_opened_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('dir_path', name='uq_project_dir')
    )
    with op.batch_alter_table('project_memory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_memory_project'))

    op.drop_table('project_memory')
    with op.batch_alter_table('task_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_steps_task'))

    op.drop_table('task_steps')
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generations_target'))

    op.drop_table('generations')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_characters_project'))

    op.drop_table('characters')
    with op.batch_alter_table('task_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_events_task_seq'))

    op.drop_table('task_events')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_target'))

    op.drop_table('conversations')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_project'))

    op.drop_table('tasks')
    with op.batch_alter_table('project_agent_prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_agent_prompt_project'))

    op.drop_table('project_agent_prompts')
    op.drop_table('projects')
    with op.batch_alter_table('artifact_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drafts_conv'))

    op.drop_table('artifact_drafts')
    with op.batch_alter_table('project_prompt_snippets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_prompt_snippet_project'))

    op.drop_table('project_prompt_snippets')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conv'))

    op.drop_table('messages')
    op.drop_table('conversation_memory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_memory',
    sa.Column('conversation_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=False),
    sa.Column('open_questions', sqlite.JSON(), nullable=False),
    sa.Column('decisions', sqlite.JSON(), nullable=False),
    sa.Column('folded_turns', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('conversation_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('turn_no', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=16), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('token_count', sa.INTEGER(), nullable=False),
    sa.Column('folded', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'turn_no', name=op.f('uq_message_turn'))
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conv'), ['conversation_id'], unique=False)

    op.create_table('project_prompt_snippets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_code', sa.VARCHAR(length=64), nullable=False),
    sa.Column('code', sa.VARCHAR(length=64), nullable=False),
    sa.Column('kind', sa.VARCHAR(length=16), nullable=False),
    sa.Column('slot', sa.VARCHAR(length=32), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('sort_no', sa.INTEGER(), nullable=False),
    sa.Column('remark', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_code', 'code', name=op.f('uq_project_prompt_snippet'))
    )
    with op.batch_alter_table('project_prompt_snippets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_prompt_snippet_project'), ['project_code', 'kind'], unique=False)

    op.create_table('artifact_drafts',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('conversation_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('target_path', sa.VARCHAR(length=512), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('based_on_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drafts_conv'), ['conversation_id'], unique=False)

    op.create_table('projects',
    sa.Column('code', sa.VARCHAR(length=64), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('dir_path', sa.VARCHAR(length=512), nullable=False),
    sa.Column('style', sqlite.JSON(), nullable=False),
    sa.Column('defaults', sqlite.JSON(), nullable=False),
    sa.Column('pose_template', sa.VARCHAR(length=512), nullable=True),
    sa.Column('art_bible', sa.VARCHAR(length=255), nullable=False),
    sa.Column('review_mode', sa.VARCHAR(length=16), nullable=False),
    sa.Column('state', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('project_agent_prompts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_code', sa.VARCHAR(length=64), nullable=False),
    sa.Column('agent_code', sa.VARCHAR(length=64), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_code', 'agent_code', name=op.f('uq_project_agent_prompt'))
    )
    with op.batch_alter_table('project_agent_prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_agent_prompt_project'), ['project_code'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('project_code', sa.VARCHAR(length=64), nullable=False),
    sa.Column('target_kind', sa.VARCHAR(length=32), nullable=False),
    sa.Column('target_ref', sa.VARCHAR(length=128), nullable=False),
    sa.Column('stage', sa.VARCHAR(length=32), nullable=False),
    sa.Column('agent_code', sa.VARCHAR(length=64), nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('params_snapshot', sqlite.JSON(), nullable=False),
    sa.Column('result', sqlite.JSON(), nullable=False),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_project'), ['project_code'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('project_code', sa.VARCHAR(length=64), nullable=False),
    sa.Column('target_kind', sa.VARCHAR(length=32), nullable=False),
    sa.Column('target_ref', sa.VARCHAR(length=128), nullable=True),
    sa.Column('agent_code', sa.VARCHAR(length=64), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('bound_provider_model_id', sa.INTEGER(), nullable=True),
    sa.Column('bound_at', sa.DATETIME(), nullable=True),
    sa.Column('rebind_count', sa.INTEGER(), nullable=False),
    sa.Column('rebind_reason', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['bound_provider_model_id'], ['provider_models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_target'), ['project_code', 'target_kind', 'target_ref'], unique=False)

    op.create_table('task_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('seq', sa.INTEGER(), nullable=False),
    sa.Column('ts', sa.DATETIME(), nullable=False),
    sa.Column('level', sa.VARCHAR(length=16), nullable=False),
    sa.Column('event', sa.VARCHAR(length=64), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('payload', sqlite.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_events_task_seq'), ['task_id', 'seq'], unique=False)

    op.create_table('characters',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('project_code', sa.VARCHAR(length=64), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('dir_path', sa.VARCHAR(length=512), nullable=False),
    sa.Column('state', sa.VARCHAR(length=32), nullable=False),
    sa.Column('spec_path', sa.VARCHAR(length=512), nullable=True),
    sa.Column('hard_constraints', sqlite.JSON(), nullable=False),
    sa.Column('params', sqlite.JSON(), nullable=False),
    sa.Column('gate_spec_confirmed_at', sa.DATETIME(), nullable=True),
    sa.Column('gate_render_confirmed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_code', 'name', name=op.f('uq_character_name'))
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_characters_project'), ['project_code'], unique=False)

    op.create_table('generations',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('project_code', sa.VARCHAR(length=64), nullable=False),
    sa.Column('target_kind', sa.VARCHAR(length=32), nullable=False),
    sa.Column('target_ref', sa.VARCHAR(length=128), nullable=False),
    sa.Column('stage', sa.VARCHAR(length=32), nullable=False),
    sa.Column('variant', sa.VARCHAR(length=64), nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=512), nullable=False),
    sa.Column('file_hash', sa.VARCHAR(length=64), nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), nullable=False),
    sa.Column('source', sa.VARCHAR(length=32), nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('asset_spec', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generations_target'), ['project_code', 'target_kind', 'target_ref'], unique=False)

    op.create_table('task_steps',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('step_no', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('progress', sa.FLOAT(), nullable=False),
    sa.Column('external_task_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('result', sqlite.JSON(), nullable=False),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_steps_task'), ['task_id'], unique=False)

    op.create_table('project_memory',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('project_code', sa.VARCHAR(length=64), nullable=False),
    sa.Column('kind', sa.VARCHAR(length=16), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('content_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('source_conversation_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_code', 'content_hash', name=op.f('uq_project_memory'))
    )
    with op.batch_alter_table('project_memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_memory_project'), ['project_code'], unique=False)

    op.drop_table('project_registry')
    # ### end Alembic commands ###
