"""init runtime schema

Revision ID: 3b3ada13b09f
Revises: 
Create Date: 2026-08-30 02:33:02.606664
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op



revision: str = '3b3ada13b09f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('artifact_drafts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('target_path', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('based_on_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact_drafts', schema=None) as batch_op:
        batch_op.create_index('ix_drafts_conv', ['conversation_id'], unique=False)

    op.create_table('characters',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('dir_path', sa.String(length=512), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('spec_path', sa.String(length=512), nullable=True),
    sa.Column('hard_constraints', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('gate_spec_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('gate_render_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_code', 'name', name='uq_character_name')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index('ix_characters_project', ['project_code'], unique=False)

    op.create_table('conversation_memory',
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('open_questions', sa.JSON(), nullable=False),
    sa.Column('decisions', sa.JSON(), nullable=False),
    sa.Column('folded_turns', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('generations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_code', sa.String(length=64), nullable=False),
    sa.Column('target_kind', sa.String(length=32), nullable=False),
    sa.Column('target_ref', sa.String(length=128), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('variant', sa.String(length=64), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('asset_spec', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.create_index('ix_generations_target', ['project_code', 'target_kind', 'target_ref'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('turn_no', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('folded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'turn_no', name='uq_message_turn')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_conv', ['conversation_id'], unique=False)

    op.create_table('project_agent_prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_code', sa.String(length=64), nullable=False),
    sa.Column('agent_code', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_code', 'agent_code', name='uq_project_agent_prompt')
    )
    with op.batch_alter_table('project_agent_prompts', schema=None) as batch_op:
        batch_op.create_index('ix_project_agent_prompt_project', ['project_code'], unique=False)

    op.create_table('project_memory',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_code', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('source_conversation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_code', 'content_hash', name='uq_project_memory')
    )
    with op.batch_alter_table('project_memory', schema=None) as batch_op:
        batch_op.create_index('ix_project_memory_project', ['project_code'], unique=False)

    op.create_table('project_prompt_snippets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_code', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('slot', sa.String(length=32), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_no', sa.Integer(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_code', 'code', name='uq_project_prompt_snippet')
    )
    with op.batch_alter_table('project_prompt_snippets', schema=None) as batch_op:
        batch_op.create_index('ix_project_prompt_snippet_project', ['project_code', 'kind'], unique=False)

    op.create_table('projects',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('dir_path', sa.String(length=512), nullable=False),
    sa.Column('style', sa.JSON(), nullable=False),
    sa.Column('defaults', sa.JSON(), nullable=False),
    sa.Column('pose_template', sa.String(length=512), nullable=True),
    sa.Column('art_bible', sa.String(length=255), nullable=False),
    sa.Column('review_mode', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('providers',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('driver', sa.String(length=32), nullable=False),
    sa.Column('auth_style', sa.String(length=16), nullable=False),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('route_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('agent_code', sa.String(length=64), nullable=False),
    sa.Column('provider_code', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.String(length=128), nullable=True),
    sa.Column('group_name', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('used_delta', sa.Integer(), nullable=True),
    sa.Column('limit_kind', sa.String(length=16), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('conversation_id', sa.String(length=64), nullable=True),
    sa.Column('project_code', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('route_logs', schema=None) as batch_op:
        batch_op.create_index('ix_route_logs_task', ['task_id'], unique=False)
        batch_op.create_index('ix_route_logs_ts', ['ts'], unique=False)

    op.create_table('task_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_events', schema=None) as batch_op:
        batch_op.create_index('ix_task_events_task_seq', ['task_id', 'seq'], unique=False)

    op.create_table('task_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('external_task_id', sa.String(length=128), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_steps', schema=None) as batch_op:
        batch_op.create_index('ix_task_steps_task', ['task_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_code', sa.String(length=64), nullable=False),
    sa.Column('target_kind', sa.String(length=32), nullable=False),
    sa.Column('target_ref', sa.String(length=128), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('agent_code', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('params_snapshot', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('ix_tasks_project', ['project_code'], unique=False)

    op.create_table('provider_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_code', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('driver', sa.String(length=32), nullable=True),
    sa.Column('api_path', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_no', sa.Integer(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_code'], ['providers.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_code', 'model_id', name='uq_provider_model')
    )
    with op.batch_alter_table('provider_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_models_provider_code'), ['provider_code'], unique=False)

    op.create_table('circuit_breakers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_model_id', sa.Integer(), nullable=False),
    sa.Column('open_until', sa.DateTime(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('last_reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_model_id'], ['provider_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_model_id', name='uq_breaker')
    )
    with op.batch_alter_table('circuit_breakers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_circuit_breakers_provider_model_id'), ['provider_model_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_code', sa.String(length=64), nullable=False),
    sa.Column('target_kind', sa.String(length=32), nullable=False),
    sa.Column('target_ref', sa.String(length=128), nullable=True),
    sa.Column('agent_code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('bound_provider_model_id', sa.Integer(), nullable=True),
    sa.Column('bound_at', sa.DateTime(), nullable=True),
    sa.Column('rebind_count', sa.Integer(), nullable=False),
    sa.Column('rebind_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bound_provider_model_id'], ['provider_models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('ix_conversations_target', ['project_code', 'target_kind', 'target_ref'], unique=False)

    op.create_table('model_limits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_model_id', sa.Integer(), nullable=False),
    sa.Column('limit_kind', sa.String(length=16), nullable=False),
    sa.Column('max_value', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=64), nullable=False),
    sa.Column('period_expr', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['provider_model_id'], ['provider_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_model_id', 'limit_kind', name='uq_model_limit')
    )
    with op.batch_alter_table('model_limits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_limits_provider_model_id'), ['provider_model_id'], unique=False)

    op.create_table('provider_agent_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_code', sa.String(length=64), nullable=False),
    sa.Column('provider_model_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['provider_model_id'], ['provider_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_code', 'provider_model_id', name='uq_pam')
    )
    with op.batch_alter_table('provider_agent_models', schema=None) as batch_op:
        batch_op.create_index('ix_pam_agent', ['agent_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_agent_models_provider_model_id'), ['provider_model_id'], unique=False)

    op.create_table('usage_counters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_model_id', sa.Integer(), nullable=False),
    sa.Column('limit_kind', sa.String(length=16), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('used_value', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_model_id'], ['provider_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_model_id', 'limit_kind', 'window_start', name='uq_usage_window')
    )
    with op.batch_alter_table('usage_counters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_counters_provider_model_id'), ['provider_model_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_counters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_counters_provider_model_id'))

    op.drop_table('usage_counters')
    with op.batch_alter_table('provider_agent_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_agent_models_provider_model_id'))
        batch_op.drop_index('ix_pam_agent')

    op.drop_table('provider_agent_models')
    with op.batch_alter_table('model_limits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_limits_provider_model_id'))

    op.drop_table('model_limits')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_conversations_target')

    op.drop_table('conversations')
    with op.batch_alter_table('circuit_breakers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_circuit_breakers_provider_model_id'))

    op.drop_table('circuit_breakers')
    with op.batch_alter_table('provider_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_models_provider_code'))

    op.drop_table('provider_models')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_project')

    op.drop_table('tasks')
    with op.batch_alter_table('task_steps', schema=None) as batch_op:
        batch_op.drop_index('ix_task_steps_task')

    op.drop_table('task_steps')
    with op.batch_alter_table('task_events', schema=None) as batch_op:
        batch_op.drop_index('ix_task_events_task_seq')

    op.drop_table('task_events')
    with op.batch_alter_table('route_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_route_logs_ts')
        batch_op.drop_index('ix_route_logs_task')

    op.drop_table('route_logs')
    op.drop_table('providers')
    op.drop_table('projects')
    with op.batch_alter_table('project_prompt_snippets', schema=None) as batch_op:
        batch_op.drop_index('ix_project_prompt_snippet_project')

    op.drop_table('project_prompt_snippets')
    with op.batch_alter_table('project_memory', schema=None) as batch_op:
        batch_op.drop_index('ix_project_memory_project')

    op.drop_table('project_memory')
    with op.batch_alter_table('project_agent_prompts', schema=None) as batch_op:
        batch_op.drop_index('ix_project_agent_prompt_project')

    op.drop_table('project_agent_prompts')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_conv')

    op.drop_table('messages')
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.drop_index('ix_generations_target')

    op.drop_table('generations')
    op.drop_table('conversation_memory')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index('ix_characters_project')

    op.drop_table('characters')
    with op.batch_alter_table('artifact_drafts', schema=None) as batch_op:
        batch_op.drop_index('ix_drafts_conv')

    op.drop_table('artifact_drafts')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
