"""usage accounting fields and credit costs

Revision ID: a7068caf07cf
Revises: 3b3ada13b09f
Create Date: 2026-08-30 03:01:47.709105
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op



revision: str = 'a7068caf07cf'
down_revision: str | None = '3b3ada13b09f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('params', sa.JSON(), nullable=False, server_default='{}'))

    with op.batch_alter_table('usage_counters', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('window_key', sa.String(length=32), nullable=False, server_default='')
        )
        batch_op.add_column(sa.Column('remaining_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('exhausted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column('source', sa.String(length=16), nullable=False, server_default='local')
        )
        batch_op.drop_constraint(batch_op.f('uq_usage_window'), type_='unique')
        batch_op.create_unique_constraint('uq_usage_window', ['provider_model_id', 'limit_kind', 'window_key'])
        batch_op.drop_column('window_start')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_counters', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('window_start', sa.DATETIME(), nullable=False, server_default='1970-01-01')
        )
        batch_op.drop_constraint('uq_usage_window', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_usage_window'), ['provider_model_id', 'limit_kind', 'window_start'])
        batch_op.drop_column('source')
        batch_op.drop_column('exhausted_at')
        batch_op.drop_column('remaining_value')
        batch_op.drop_column('window_key')

    with op.batch_alter_table('provider_models', schema=None) as batch_op:
        batch_op.drop_column('params')

    # ### end Alembic commands ###
