"""init config schema

Revision ID: 93a010edb77a
Revises: 
Create Date: 2026-08-30 02:29:00.366340
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op



revision: str = '93a010edb77a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_categories',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('dir_name', sa.String(length=64), nullable=False),
    sa.Column('sort_no', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('meshy_actions',
    sa.Column('action_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('sub_category', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_table('model_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=64), nullable=False),
    sa.Column('driver', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('api_path', sa.String(length=255), nullable=True),
    sa.Column('auth_style', sa.String(length=16), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor', 'plan', 'model_id', name='uq_model_catalog')
    )
    op.create_table('workflow_defs',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('target_kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('states', sa.JSON(), nullable=False),
    sa.Column('transitions', sa.JSON(), nullable=False),
    sa.Column('gates', sa.JSON(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_defs')
    op.drop_table('model_catalog')
    op.drop_table('meshy_actions')
    op.drop_table('asset_categories')
    # ### end Alembic commands ###
